//! Compile-time string obfuscation via XOR encryption.
//!
//! Provides the `obf!()` macro that XOR-encrypts string literals at compile time
//! using a per-build random key. The encrypted bytes are stored in the binary;
//! decryption happens at runtime with zero allocation (stack buffer).
//!
//! Usage:
//! ```ignore
//! let route = obf!("/api/remember");
//! let env_var = obf!("SHODH_API_KEYS");
//! ```
//!
//! Under `--features fortress`, strings are encrypted in the binary.
//! Without the feature, `obf!()` is a passthrough (returns &str directly).

/// Per-build XOR key — generated by build.rs from random seed.
/// Each `cargo build` produces a different key, so the encrypted bytes
/// differ across builds (prevents known-plaintext attacks).
const FORTRESS_KEY: [u8; 32] = {
    // Build.rs sets VELD_BUILD_NUMBER and VELD_FORTRESS_SEED for each build.
    // We derive a per-build fallback key from the build number here.
    // This is NOT a secret — it's a speed bump against `strings`, not crypto.
    let ts = env!("VELD_BUILD_NUMBER");
    let b = ts.as_bytes();
    let mut key = [0x5Au8; 32];
    let mut i = 0;
    while i < 32 {
        key[i] = key[i]
            .wrapping_add(b[i % b.len()])
            .wrapping_mul(0x9E)
            .wrapping_add(i as u8);
        i += 1;
    }
    key
};

/// XOR-decrypt a byte slice using the fortress key.
/// Returns a stack-allocated string (no heap allocation for short strings).
#[inline(always)]
pub fn decrypt(encrypted: &[u8]) -> String {
    let mut buf = Vec::with_capacity(encrypted.len());
    for (i, &byte) in encrypted.iter().enumerate() {
        buf.push(byte ^ FORTRESS_KEY[i % FORTRESS_KEY.len()]);
    }
    // Safety: we encrypted valid UTF-8, so decryption produces valid UTF-8
    unsafe { String::from_utf8_unchecked(buf) }
}

/// Compile-time string encryption macro.
///
/// In fortress mode: encrypts the string at compile time, decrypts at runtime.
/// The encrypted bytes appear as opaque binary data in the executable.
///
/// # Implementation
/// Uses a const block to perform XOR encryption at compile time.
/// The resulting byte array is stored in .rodata as encrypted bytes.
/// At runtime, `decrypt()` XORs them back to recover the original string.
#[macro_export]
macro_rules! obf {
    ($s:expr) => {{
        // Encrypt at compile time using const evaluation
        const ENCRYPTED: &[u8] = {
            const INPUT: &[u8] = $s.as_bytes();
            const KEY: &[u8; 32] = &$crate::fortress::strings::FORTRESS_KEY_PUB;
            // We can't return a dynamically-sized array from const context,
            // so we use a fixed-size buffer and encode the length.
            // For strings up to 256 bytes (covers all API routes/env vars).
            const MAX_LEN: usize = 256;
            const SENTINEL: u8 = 0xFF; // marks end of encrypted data
            const fn encrypt() -> [u8; MAX_LEN] {
                let mut buf = [SENTINEL; MAX_LEN];
                let len = INPUT.len();
                let mut i = 0;
                while i < len && i < MAX_LEN - 1 {
                    buf[i] = INPUT[i] ^ KEY[i % 32];
                    i += 1;
                }
                buf[len] = SENTINEL;
                buf
            }
            const RESULT: [u8; MAX_LEN] = encrypt();
            &RESULT
        };
        // Find the sentinel and decrypt only the meaningful bytes
        {
            let end = ENCRYPTED.iter().position(|&b| b == 0xFF).unwrap_or(ENCRYPTED.len());
            $crate::fortress::strings::decrypt(&ENCRYPTED[..end])
        }
    }};
}

/// Public key accessor for the obf! macro (must be pub for macro hygiene)
pub const FORTRESS_KEY_PUB: [u8; 32] = FORTRESS_KEY;

/// Fortress-mode tracing macros that compile to nothing.
/// In fortress builds, ALL log output is eliminated — zero strings in binary.
#[macro_export]
macro_rules! fortress_trace {
    ($($arg:tt)*) => {
        // Intentionally empty — fortress mode produces zero trace output
    };
}

#[macro_export]
macro_rules! fortress_debug {
    ($($arg:tt)*) => {};
}

#[macro_export]
macro_rules! fortress_info {
    ($($arg:tt)*) => {};
}

#[macro_export]
macro_rules! fortress_warn {
    ($($arg:tt)*) => {};
}

#[macro_export]
macro_rules! fortress_error {
    ($($arg:tt)*) => {};
}
